matrix:
  include:
    - sudo: required
      dist: trusty

language: ruby
rvm:
  - 2.2.3
before_install:
- gem install bundler -v 1.10.6
- sudo ./travis_install.sh

script:
  - ./configure --with-grpc=/opt/libgrpc && make -j6
