# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binlogdata.proto

require 'google/protobuf'

require 'query_pb'
require 'topodata_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "binlogdata.Charset" do
    optional :client, :int32, 1
    optional :conn, :int32, 2
    optional :server, :int32, 3
  end
  add_message "binlogdata.BinlogTransaction" do
    repeated :statements, :message, 1, "binlogdata.BinlogTransaction.Statement"
    optional :event_token, :message, 4, "query.EventToken"
  end
  add_message "binlogdata.BinlogTransaction.Statement" do
    optional :category, :enum, 1, "binlogdata.BinlogTransaction.Statement.Category"
    optional :charset, :message, 2, "binlogdata.Charset"
    optional :sql, :bytes, 3
  end
  add_enum "binlogdata.BinlogTransaction.Statement.Category" do
    value :BL_UNRECOGNIZED, 0
    value :BL_BEGIN, 1
    value :BL_COMMIT, 2
    value :BL_ROLLBACK, 3
    value :BL_DML_DEPRECATED, 4
    value :BL_DDL, 5
    value :BL_SET, 6
    value :BL_INSERT, 7
    value :BL_UPDATE, 8
    value :BL_DELETE, 9
  end
  add_message "binlogdata.StreamKeyRangeRequest" do
    optional :position, :string, 1
    optional :key_range, :message, 2, "topodata.KeyRange"
    optional :charset, :message, 3, "binlogdata.Charset"
  end
  add_message "binlogdata.StreamKeyRangeResponse" do
    optional :binlog_transaction, :message, 1, "binlogdata.BinlogTransaction"
  end
  add_message "binlogdata.StreamTablesRequest" do
    optional :position, :string, 1
    repeated :tables, :string, 2
    optional :charset, :message, 3, "binlogdata.Charset"
  end
  add_message "binlogdata.StreamTablesResponse" do
    optional :binlog_transaction, :message, 1, "binlogdata.BinlogTransaction"
  end
  add_message "binlogdata.BinlogSource" do
    optional :keyspace, :string, 1
    optional :shard, :string, 2
    optional :tablet_type, :enum, 3, "topodata.TabletType"
    optional :key_range, :message, 4, "topodata.KeyRange"
    repeated :tables, :string, 5
  end
end

module Binlogdata
  Charset = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.Charset").msgclass
  BinlogTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.BinlogTransaction").msgclass
  BinlogTransaction::Statement = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.BinlogTransaction.Statement").msgclass
  BinlogTransaction::Statement::Category = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.BinlogTransaction.Statement.Category").enummodule
  StreamKeyRangeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.StreamKeyRangeRequest").msgclass
  StreamKeyRangeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.StreamKeyRangeResponse").msgclass
  StreamTablesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.StreamTablesRequest").msgclass
  StreamTablesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.StreamTablesResponse").msgclass
  BinlogSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("binlogdata.BinlogSource").msgclass
end
