# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: throttlerservice.proto

require 'google/protobuf'

require 'throttlerdata_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Throttlerservice
end
