# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mysqlctl.proto for package 'mysqlctl'
# Original file comments:
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreedto in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file contains the service definition for making management API
# calls to mysqlctld.
#

require 'grpc'
require 'mysqlctl_pb'

module Mysqlctl
  module MysqlCtl
    # MysqlCtl is the service definition
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mysqlctl.MysqlCtl'

      rpc :Start, StartRequest, StartResponse
      rpc :Shutdown, ShutdownRequest, ShutdownResponse
      rpc :RunMysqlUpgrade, RunMysqlUpgradeRequest, RunMysqlUpgradeResponse
      rpc :ReinitConfig, ReinitConfigRequest, ReinitConfigResponse
      rpc :RefreshConfig, RefreshConfigRequest, RefreshConfigResponse
    end

    Stub = Service.rpc_stub_class
  end
end
