# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: throttlerdata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "throttlerdata.MaxRatesRequest" do
  end
  add_message "throttlerdata.MaxRatesResponse" do
    map :rates, :string, :int64, 1
  end
  add_message "throttlerdata.SetMaxRateRequest" do
    optional :rate, :int64, 1
  end
  add_message "throttlerdata.SetMaxRateResponse" do
    repeated :names, :string, 1
  end
  add_message "throttlerdata.Configuration" do
    optional :target_replication_lag_sec, :int64, 1
    optional :max_replication_lag_sec, :int64, 2
    optional :initial_rate, :int64, 3
    optional :max_increase, :double, 4
    optional :emergency_decrease, :double, 5
    optional :min_duration_between_increases_sec, :int64, 6
    optional :max_duration_between_increases_sec, :int64, 7
    optional :min_duration_between_decreases_sec, :int64, 8
    optional :spread_backlog_across_sec, :int64, 9
    optional :ignore_n_slowest_replicas, :int32, 10
    optional :ignore_n_slowest_rdonlys, :int32, 11
    optional :age_bad_rate_after_sec, :int64, 12
    optional :bad_rate_increase, :double, 13
    optional :max_rate_approach_threshold, :double, 14
  end
  add_message "throttlerdata.GetConfigurationRequest" do
    optional :throttler_name, :string, 1
  end
  add_message "throttlerdata.GetConfigurationResponse" do
    map :configurations, :string, :message, 1, "throttlerdata.Configuration"
  end
  add_message "throttlerdata.UpdateConfigurationRequest" do
    optional :throttler_name, :string, 1
    optional :configuration, :message, 2, "throttlerdata.Configuration"
    optional :copy_zero_values, :bool, 3
  end
  add_message "throttlerdata.UpdateConfigurationResponse" do
    repeated :names, :string, 1
  end
  add_message "throttlerdata.ResetConfigurationRequest" do
    optional :throttler_name, :string, 1
  end
  add_message "throttlerdata.ResetConfigurationResponse" do
    repeated :names, :string, 1
  end
end

module Throttlerdata
  MaxRatesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.MaxRatesRequest").msgclass
  MaxRatesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.MaxRatesResponse").msgclass
  SetMaxRateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.SetMaxRateRequest").msgclass
  SetMaxRateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.SetMaxRateResponse").msgclass
  Configuration = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.Configuration").msgclass
  GetConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.GetConfigurationRequest").msgclass
  GetConfigurationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.GetConfigurationResponse").msgclass
  UpdateConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.UpdateConfigurationRequest").msgclass
  UpdateConfigurationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.UpdateConfigurationResponse").msgclass
  ResetConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.ResetConfigurationRequest").msgclass
  ResetConfigurationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("throttlerdata.ResetConfigurationResponse").msgclass
end
