# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vtworkerservice.proto for package 'vtworkerservice'
# Original file comments:
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreedto in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# RPC interface for vtworker.
# The interface is very similar to the vtctld interface (see vtctlservice.proto).
#

require 'grpc'
require 'vtworkerservice_pb'

module Vtworkerservice
  module Vtworker
    # Vtworker contains the vtworker RPC calls.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'vtworkerservice.Vtworker'

      # ExecuteVtworkerCommand allows to run a vtworker command by specifying the
      # same arguments as on the command line.
      rpc :ExecuteVtworkerCommand, Vtworkerdata::ExecuteVtworkerCommandRequest, stream(Vtworkerdata::ExecuteVtworkerCommandResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
